version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/coinbase/dexter
    steps:
      - checkout
      - run: go build
      - run: make test
